### ISSUE TITLE
Response time

### ISSUE THREAD

**Issue by thvozdovic** [kleydon/prisma-session-store#57]
Hey,
I'm using this prisma session store but I noticed the response time is almost 10x longer than when using memorystore, is this expected or not?

Making a request to a non-existent page without the prisma session store takes about 40ms on average, while it takes around 450ms when the prisma store is used.

**Comment by kleydon** [comment]
Hi @thvozdovic,

Strange; hadn't encountered this.

_Authentication_ will take significantly longer than requesting a non-existent page, since it requires at least one db request/response, and possibly more than that if the page requires dynamic data. (If you're coming from using JWTs or equivalent for authentication, this "extra" db hit, for each page-load, may seem surprising.)

But as for why _this_ session store might take longer than _another_ session store - Not sure why that would be... 

Perhaps in the transpilation from typescript to javascript, optimization is not yet what it should be? 

Another though: _in-memory_ data stores are significantly faster than their alternatives. If memorystore is in-memory (as its name suggests), and the database you are using with prisma-session-store is _not_ in-memory (e.g. postgres, mysql, etc): Perhaps that could account for the speed difference?

**Comment by kleydon** [comment]
Anyone still experiencing unexpected reponse time issues with prisma-session-store?

**Comment by kleydon** [comment]
Closing for now; we can re-open if this re-surfaces.
